logging:
  level:
    org:
      springframework: ERROR
spring:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    initialization-mode: always
    platform: postgres
  sql:
    init:
      mode: always

timezone: America/Sao_Paulo