spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PWD}
  devtools:
    add-properties: false

jwt:
  secret: ${JWT_SECRET}
  expires_in: ${JWT_EXPIRES_IN}

# Open API configuration
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# Logging config
logging:
  pattern:
    console: "{\"time\": \"%d\", \"level\": \"%p\", \"source\": \"%logger{63}:%L\", \"message\": \"%m\"}%n"

app:
  cors:
    origins: 'https://www.12reinos.com'
    methods: 'GET,OPTIONS,POST,PATCH,PUT,DELETE'