spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PWD}

jwt:
  secret: ${JWT_SECRET}
  expires_in: ${JWT_EXPIRES_IN}

# Open API configuration
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false