project:
  title: @project.name@
  version: @project.version@
  description: @project.description@
spring:
  web:
    locale: en_US
    locale-resolver: fixed
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    initialization-mode: always
    platform: postgres
  sql:
    init:
      mode: always

# Config to allow execution of requests from Open API interface
server:
  tomcat:
    relaxed-query-chars: '|,{,},[,]'

# Open API configuration
springdoc:
  api-docs:
    path: /api-docs

# Limit number of calls per second
bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: /*
      rate-limits:
        - bandwidths:
            - capacity: 5
              time: 10
              unit: seconds

timezone: America/Sao_Paulo