logging:
  level:
    org:
      springframework: ERROR
spring:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    initialization-mode: always
    platform: postgres
  sql:
    init:
      mode: always

# Limit number of calls per second
bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: /*
      rate-limits:
        - bandwidths:
            - capacity: 5
              time: 10
              unit: seconds

timezone: America/Sao_Paulo