project:
  title: @project.name@
  version: @project.version@
  description: @project.description@
spring:
  web:
    locale: en_US
    locale-resolver: fixed
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  sql:
    init:
      platform: postgres

# Config to allow execution of requests from Open API interface
server:
  tomcat:
    relaxed-query-chars: '|,{,},[,]'
  port: 8080
  forward-headers-strategy: framework
#  servlet:
#    context-path: /v2

# Open API configuration
springdoc:
  api-docs:
    path: /api-docs

# Limit number of calls per second
bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: /*
      rate-limits:
        - bandwidths:
            - capacity: 5
              time: 10
              unit: seconds

timezone: America/Sao_Paulo